### ISSUE TITLE
Android 11 cannot start this app

### ISSUE THREAD

**Issue by wartw** [umer0586/AndroidSMSServer#1]
Android 11 cannot start this app

**Comment by umer0586** [comment]
@wartw 
What error you get while starting ?

**Comment by wartw** [comment]
Direct crash cannot be opened

**Comment by umer0586** [comment]
@wartw 
I never came across such issue while developing this app. I can't tell much because i dont have any crash logs to view.
You have to wait until i check the app on android 11 emulator

**Comment by wartw** [comment]
ok, waiting for you to test.  It is recommended that you add a token verification on the web so that the external IP can be directly accessed

**Comment by umer0586** [comment]
@wartw 
Okay i have found the issue causing crash on android 11. I am working on it now

**Comment by wartw** [comment]
Congratulations, I found the reason (I only saw your github project today, I really need this thing

**Comment by umer0586** [comment]
@wartw 
I have fixed the issue you can now download latest apk to install
https://github.com/umer0586/AndroidSMSServer/releases/tag/v1.3

**Comment by wartw** [comment]
![Uploading Screenshot_2021-12-21-02-29-46-566_github.umer0586.smsserver.jpg…]()

**Comment by wartw** [comment]
ui page overlap

**Comment by wartw** [comment]
Which sim will be used first for dual-SIM SMS?

**Comment by umer0586** [comment]
@wartw 
Image doesn't open. link is broken

**Comment by wartw** [comment]
![Screenshot_2021-12-21-02-29-46-566_github umer0586 smsserver](https://user-images.githubusercontent.com/15444598/146825439-9f7c6ad9-1673-434a-b983-144baafa04c7.jpg)

**Comment by umer0586** [comment]
> Which sim will be used first for dual-SIM SMS?

@wartw 
I haven't configure that settings in the app but i guess it would the one primarily selected by default sms app

**Comment by umer0586** [comment]
> ![Screenshot_2021-12-21-02-29-46-566_github umer0586 smsserver](https://user-images.githubusercontent.com/15444598/146825439-9f7c6ad9-1673-434a-b983-144baafa04c7.jpg)

This looks weird as this never happened while using emulator and real device 
I will check this tomorrow

**Comment by wartw** [comment]
I haven’t set the default sim, so I may not be able to send it. I suggest you add options to it.

**Comment by umer0586** [comment]
> I haven’t set the default sim, so I may not be able to send it. I suggest you add options to it.

@wartw Just for testing purpose let the app sends message without setting a default one and see what result you get

**Comment by umer0586** [comment]
> ui page overlap
@wartw 
Please tell 
1. overlapping occurs when app is opened for the first time ?
2. or when you press back button while using app ?

**Comment by wartw** [comment]
I overlapped when I went in

**Comment by umer0586** [comment]
> I overlapped when I went in

@wartw I have done some fixing check latest apk now 
https://github.com/umer0586/AndroidSMSServer/releases/tag/v1.3.1

**Comment by wartw** [comment]
normal now

**Comment by umer0586** [comment]
fixed : 6fae2930152afa1e032d399cc9b60229ccf908ac
