### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by xmha97** [umer0586/AndroidSMSServer#10]
Please add this app to the F-Droid.
I do not have access to Google Play.

**Comment by umer0586** [comment]
`apks` are available under [Release Section](https://github.com/umer0586/AndroidSMSServer/releases)

**Comment by xmha97** [comment]
I downloaded the app from GitHub, but in this case, the app won't update.

**Comment by umer0586** [comment]
Okay I will add it later

**Comment by xmha97** [comment]
Thanks.
