### ISSUE TITLE
Customize the sender name 

### ISSUE THREAD

**Issue by tech62** [umer0586/AndroidSMSServer#12]
How can i can customize the sender name instead of the phone number ?

Thanks !

**Comment by umer0586** [comment]
currently the app doesn't support sending sms by name. But you can maintain name and phone number mapping at client side like
```javascript
var contacts = {
  "friend1" : "03239030349",
  "friend2" : "06774045832"
};

request.post({
  url: 'http://192.168.0.102:8080/sendSMS',
  form: {
    phone: contacts["friend1"],
    message: 'hello',
  }
}, function (err, httpResponse, body) { 

  console.log(body);

 })
```

**Comment by tech62** [comment]
I wanted to use different name when sending message not using the contact name as an alias ^^
So if i've understand it's not possible :/

Another idea, i want to make a clicktocall on button (client side) who make a post request and start a call on the mobile, is it possible?

**Comment by umer0586** [comment]
> I wanted to use different name when sending message not using the contact name as an alias ^^
So if i've understand it's not possible :/

 Its not possible no app can do this !

> Another idea, i want to make a clicktocall on button (client side) who make a post request and start a call on the mobile, is it possible?

Yes its possible but not with this app
