### ISSUE TITLE
App Crash on settings

### ISSUE THREAD

**Issue by bufferUnderrun** [umer0586/AndroidSMSServer#13]
Hi,

First, thanks for your app, it feets my needs perfectly !!

Then, the app crash just after opening the settings tab on my old Pixel3/Android12.
But, it works on my new Pixel6/Android13.

Thanks for your help

**Comment by umer0586** [comment]
Download [v3.3.0](https://github.com/umer0586/AndroidSMSServer/releases/tag/v3.3.0) (latest release) and install it on your Pixel3/Android12. When crash happens app will automatically open email client and ask you to send crash report (text file). Just send that text file so that I can see what is causing crash

**Comment by bufferUnderrun** [comment]
The crash report

`{"REPORT_ID":"fc13652f-2026-44ed-b6fd-11c4dd4b2c72","APP_VERSION_CODE":17,"APP_VERSION_NAME":"3.3.0","PACKAGE_NAME":"github.umer0586.smsserver","FILE_PATH":"\/data\/user\/0\/github.umer0586.smsserver\/files","PHONE_MODEL":"Pixel 3","BRAND":"google","PRODUCT":"blueline","ANDROID_VERSION":"12","BUILD":{"BOARD":"blueline","BOOTLOADER":"b1c1-0.4-7617406","BRAND":"google","CPU_ABI":"arm64-v8a","CPU_ABI2":"","DEVICE":"blueline","DISPLAY":"SP1A.210812.016.C2","FINGERPRINT":"google\/blueline\/blueline:12\/SP1A.210812.016.C2\/8618562:user\/release-keys","HARDWARE":"blueline","HOST":"abfarm-release-rbe-64-00023","ID":"SP1A.210812.016.C2","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"Google","MODEL":"Pixel 3","ODM_SKU":"G013A","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"blueline","RADIO":"unknown","SKU":"G013A","SOC_MANUFACTURER":"Qualcomm","SOC_MODEL":"SDM845","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":["arm64-v8a"],"SUPPORTED_ABIS":["arm64-v8a","armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1653001377000,"TYPE":"user","UNKNOWN":"unknown","USER":"android-build","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","INCREMENTAL":"8618562","MEDIA_PERFORMANCE_CLASS":0,"PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"12","RELEASE_OR_CODENAME":"12","SDK":"31","SDK_INT":31,"SECURITY_PATCH":"2021-10-05"}},"TOTAL_MEM_SIZE":55379472384,"AVAILABLE_MEM_SIZE":43928518656,"BUILD_CONFIG":{"APPLICATION_ID":"github.umer0586.smsserver","BUILD_TYPE":"debug","DEBUG":true,"VERSION_CODE":17,"VERSION_NAME":"3.3.0"},"CUSTOM_DATA":{},"IS_SILENT":false,"STACK_TRACE":"java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available\n","INITIAL_CONFIGURATION":{"colorMode":10,"densityDpi":440,"fontScale":1,"fontWeightAdjustment":0,"hardKeyboardHidden":"HARDKEYBOARDHIDDEN_YES","keyboard":"KEYBOARD_NOKEYS","keyboardHidden":"KEYBOARDHIDDEN_NO","locale":"fr_FR","mcc":208,"mnc":15,"navigation":"NAVIGATION_NONAV","navigationHidden":"NAVIGATIONHIDDEN_YES","orientation":"ORIENTATION_PORTRAIT","screenHeightDp":741,"screenLayout":"SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO","screenWidthDp":392,"seq":56,"smallestScreenWidthDp":392,"touchscreen":"TOUCHSCREEN_FINGER","uiMode":"UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO","userSetLocale":false},"CRASH_CONFIGURATION":{"colorMode":10,"densityDpi":440,"fontScale":1,"fontWeightAdjustment":0,"hardKeyboardHidden":"HARDKEYBOARDHIDDEN_YES","keyboard":"KEYBOARD_NOKEYS","keyboardHidden":"KEYBOARDHIDDEN_NO","locale":"fr_FR","mcc":208,"mnc":15,"navigation":"NAVIGATION_NONAV","navigationHidden":"NAVIGATIONHIDDEN_YES","orientation":"ORIENTATION_PORTRAIT","screenHeightDp":741,"screenLayout":"SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO","screenWidthDp":392,"seq":56,"smallestScreenWidthDp":392,"touchscreen":"TOUCHSCREEN_FINGER","uiMode":"UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO","userSetLocale":false},"DISPLAY":{"0":{"currentSizeRange":{"smallest":[1080,970],"largest":[2160,2039]},"flags":"FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE","metrics":{"density":2.75,"densityDpi":440,"scaledDensity":"x2.75","widthPixels":1080,"heightPixels":2116,"xdpi":442.45098876953125,"ydpi":442.45098876953125},"realMetrics":{"density":2.75,"densityDpi":440,"scaledDensity":"x2.75","widthPixels":1080,"heightPixels":2160,"xdpi":442.45098876953125,"ydpi":442.45098876953125},"name":"Écran intégré","realSize":[1080,2160],"rectSize":[0,0,1080,2116],"size":[1080,2116],"rotation":"ROTATION_0","isValid":true,"orientation":0,"refreshRate":60.000003814697266,"height":2116,"width":1080,"pixelFormat":1}},"USER_COMMENT":null,"USER_EMAIL":"N\/A","USER_APP_START_DATE":"2022-12-29T18:17:18.287+01:00","USER_CRASH_DATE":"2022-12-29T18:17:20.382+01:00","DUMPSYS_MEMINFO":"","LOGCAT":"--------- beginning of crash\n12-29 18:11:27.275 E\/AndroidRuntime(30146): FATAL EXCEPTION: main\n12-29 18:11:27.275 E\/AndroidRuntime(30146): Process: github.umer0586.smsserver, PID: 30146\n12-29 18:11:27.275 E\/AndroidRuntime(30146): java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available\n--------- beginning of main\n12-29 18:17:17.730 I\/r0586.smsserve( 3224): Late-enabling -Xcheck:jni\n12-29 18:17:17.839 D\/ProcessState( 3224): Binder ioctl to enable oneway spam detection failed: Invalid argument\n12-29 18:17:17.858 D\/CompatibilityChangeReporter( 3224): Compat change id reported: 171979766; UID 10264; state: ENABLED\n12-29 18:17:17.872 W\/ziparchive( 3224): Unable to open '\/data\/app\/~~SBHd92Bb6SSHK0cSlhVHAg==\/github.umer0586.smsserver-sCdVrZHE_QJ4ngOMzeEXKQ==\/base.dm': No such file or directory\n12-29 18:17:17.872 W\/ziparchive( 3224): Unable to open '\/data\/app\/~~SBHd92Bb6SSHK0cSlhVHAg==\/github.umer0586.smsserver-sCdVrZHE_QJ4ngOMzeEXKQ==\/base.dm': No such file or directory\n12-29 18:17:18.099 D\/nativeloader( 3224): Configuring classloader-namespace for other apk \/data\/app\/~~SBHd92Bb6SSHK0cSlhVHAg==\/github.umer0586.smsserver-sCdVrZHE_QJ4ngOMzeEXKQ==\/base.apk. target_sdk_version=33, uses_libraries=, library_path=\/data\/app\/~~SBHd92Bb6SSHK0cSlhVHAg==\/github.umer0586.smsserver-sCdVrZHE_QJ4ngOMzeEXKQ==\/lib\/arm64, permitted_path=\/data:\/mnt\/expand:\/data\/user\/0\/github.umer0586.smsserver\n12-29 18:17:18.111 V\/GraphicsEnvironment( 3224): ANGLE Developer option for 'github.umer0586.smsserver' set to: 'default'\n12-29 18:17:18.111 V\/GraphicsEnvironment( 3224): App is not on the allowlist for updatable production driver.\n12-29 18:17:18.113 D\/NetworkSecurityConfig( 3224): No Network Security Config specified, using platform default\n12-29 18:17:18.113 D\/NetworkSecurityConfig( 3224): No Network Security Config specified, using platform default\n12-29 18:17:18.174 I\/ACRA    ( 3224): ACRA is enabled for github.umer0586.smsserver, initializing...\n12-29 18:17:18.396 W\/r0586.smsserve( 3224): Accessing hidden method Landroid\/view\/View;->computeFitSystemWindows(Landroid\/graphics\/Rect;Landroid\/graphics\/Rect;)Z (unsupported, reflection, allowed)\n12-29 18:17:18.396 W\/r0586.smsserve( 3224): Accessing hidden method Landroid\/view\/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)\n12-29 18:17:18.432 D\/CompatibilityChangeReporter( 3224): Compat change id reported: 171228096; UID 10264; state: ENABLED\n12-29 18:17:18.512 I\/AdrenoGLES-0( 3224): QUALCOMM build                   : 781e7d0, I46ff5fc46f\n12-29 18:17:18.512 I\/AdrenoGLES-0( 3224): Build Date                       : 12\/01\/20\n12-29 18:17:18.512 I\/AdrenoGLES-0( 3224): OpenGL ES Shader Compiler Version: EV031.31.04.01\n12-29 18:17:18.512 I\/AdrenoGLES-0( 3224): Local Branch                     : QPR1\n12-29 18:17:18.512 I\/AdrenoGLES-0( 3224): Remote Branch                    : \n12-29 18:17:18.512 I\/AdrenoGLES-0( 3224): Remote Branch                    : \n12-29 18:17:18.512 I\/AdrenoGLES-0( 3224): Reconstruct Branch               : \n12-29 18:17:18.512 I\/AdrenoGLES-0( 3224): Build Config                     : C P 11.0.1 AArch64\n12-29 18:17:18.512 I\/AdrenoGLES-0( 3224): Driver Path                      : \/vendor\/lib64\/egl\/libGLESv2_adreno.so\n12-29 18:17:18.530 D\/ServiceBindHelper : ServerFragment( 3224): ON_CREATE\n12-29 18:17:18.534 I\/AdrenoGLES-0( 3224): PFP: 0x016ee190, ME: 0x00000000\n12-29 18:17:18.536 W\/AdrenoUtils( 3224): <ReadGpuID_from_sysfs:197>: Failed to open \/sys\/class\/kgsl\/kgsl-3d0\/gpu_model\n12-29 18:17:18.536 W\/AdrenoUtils( 3224): <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path\n12-29 18:17:18.556 D\/ServiceBindHelper : ServerFragment( 3224): ON_START\n12-29 18:17:18.556 D\/ServiceBindHelper : ServerFragment( 3224): ON_RESUME\n12-29 18:17:18.556 D\/ServiceBindHelper( 3224): bindToService()\n12-29 18:17:18.563 D\/hw-ProcessState( 3224): Binder ioctl to enable oneway spam detection failed: Invalid argument\n12-29 18:17:18.575 I\/Gralloc4( 3224): mapper 4.x is not supported\n12-29 18:17:18.577 W\/Gralloc3( 3224): mapper 3.x is not supported\n12-29 18:17:18.584 W\/Gralloc4( 3224): allocator 4.x is not supported\n12-29 18:17:18.585 W\/Gralloc3( 3224): allocator 3.x is not supported\n12-29 18:17:18.678 D\/SMSService( 3224): onCreate() called\n12-29 18:17:18.678 D\/SMSService( 3224): createNotificationChannel() called\n12-29 18:17:18.681 D\/MessageReceiver( 3224): registerEvents() called\n12-29 18:17:18.689 D\/ServiceBindHelper( 3224): onServiceConnected() \n12-29 18:17:18.689 D\/ServerFragment( 3224): onServiceConnected() \n12-29 18:17:20.291 D\/ServiceBindHelper : ServerFragment( 3224): ON_PAUSE\n12-29 18:17:20.291 D\/ServiceBindHelper( 3224): unBindFromService() \n12-29 18:17:20.292 D\/ServerFragment( 3224): onPause() called\n12-29 18:17:20.302 D\/AndroidRuntime( 3224): Shutting down VM\n12-29 18:17:20.302 E\/AndroidRuntime( 3224): FATAL EXCEPTION: main\n12-29 18:17:20.302 E\/AndroidRuntime( 3224): Process: github.umer0586.smsserver, PID: 3224\n12-29 18:17:20.302 E\/AndroidRuntime( 3224): java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available\n12-29 18:17:20.302 E\/ACRA    ( 3224): ACRA caught a NoClassDefFoundError for github.umer0586.smsserver\n12-29 18:17:20.302 E\/ACRA    ( 3224): java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available\n","INSTALLATION_ID":"b88893b1-6f04-434f-8005-ad94a1da6a7c","DEVICE_FEATURES":{"android.hardware.sensor.proximity":true,"com.verizon.hardware.telephony.lte":true,"com.verizon.hardware.telephony.ehrpd":true,"android.hardware.sensor.accelerometer":true,"android.software.controls":true,"android.hardware.faketouch":true,"com.google.android.feature.D2D_CABLE_MIGRATION_FEATURE":true,"android.hardware.telephony.euicc":true,"android.hardware.reboot_escrow":true,"android.hardware.usb.accessory":true,"android.hardware.telephony.cdma":true,"android.software.backup":true,"android.hardware.touchscreen":true,"android.hardware.touchscreen.multitouch":true,"android.software.print":true,"android.software.activities_on_secondary_displays":true,"android.hardware.wifi.rtt":true,"com.google.android.feature.PIXEL_2017_EXPERIENCE":true,"android.software.voice_recognizers":true,"android.software.picture_in_picture":true,"android.hardware.fingerprint":true,"android.hardware.sensor.gyroscope":true,"android.hardware.audio.low_latency":true,"android.software.vulkan.deqp.level":true,"android.software.cant_save_state":true,"com.google.android.feature.PIXEL_2018_EXPERIENCE":true,"android.hardware.security.model.compatible":true,"android.hardware.opengles.aep":true,"android.hardware.bluetooth":true,"android.hardware.camera.autofocus":true,"com.google.android.feature.GOOGLE_BUILD":true,"android.hardware.telephony.gsm":true,"android.hardware.telephony.ims":true,"android.software.sip.voip":true,"android.software.opengles.deqp.level":true,"android.hardware.vr.high_performance":true,"android.hardware.usb.host":true,"android.hardware.audio.output":true,"android.software.verified_boot":true,"android.hardware.camera.flash":true,"android.hardware.camera.front":true,"android.hardware.sensor.hifi_sensors":true,"android.hardware.se.omapi.uicc":true,"android.hardware.strongbox_keystore":true,"android.hardware.screen.portrait":true,"android.hardware.nfc":true,"com.google.android.feature.TURBO_PRELOAD":true,"android.hardware.vr.headtracking":true,"com.nxp.mifare":true,"android.hardware.sensor.stepdetector":true,"android.software.home_screen":true,"android.hardware.context_hub":true,"android.hardware.microphone":true,"android.software.autofill":true,"android.software.securely_removes_users":true,"android.software.vr.mode":true,"com.google.android.feature.PIXEL_EXPERIENCE":true,"android.hardware.bluetooth_le":true,"android.hardware.sensor.compass":true,"com.google.android.feature.GOOGLE_FI_BUNDLED":true,"android.hardware.touchscreen.multitouch.jazzhand":true,"android.hardware.sensor.barometer":true,"android.software.app_widgets":true,"android.hardware.telephony.carrierlock":true,"android.software.input_methods":true,"android.hardware.sensor.light":true,"android.hardware.vulkan.version":true,"android.software.companion_device_setup":true,"android.software.device_admin":true,"com.google.android.feature.WELLBEING":true,"android.hardware.wifi.passpoint":true,"android.hardware.camera":true,"android.hardware.device_unique_attestation":true,"android.hardware.screen.landscape":true,"android.software.device_id_attestation":true,"com.google.android.feature.AER_OPTIMIZED":true,"android.hardware.ram.normal":true,"android.software.managed_users":true,"android.software.webview":true,"android.hardware.sensor.stepcounter":true,"android.hardware.camera.capability.manual_post_processing":true,"android.hardware.camera.any":true,"android.hardware.camera.capability.raw":true,"android.hardware.vulkan.compute":true,"android.software.connectionservice":true,"android.hardware.touchscreen.multitouch.distinct":true,"android.hardware.location.network":true,"android.software.cts":true,"android.software.sip":true,"android.hardware.camera.capability.manual_sensor":true,"com.google.hardware.camera.easel_2018":true,"android.software.app_enumeration":true,"com.google.android.apps.dialer.SUPPORTED":true,"android.hardware.camera.level.full":true,"android.hardware.identity_credential":true,"android.hardware.wifi.direct":true,"android.software.live_wallpaper":true,"com.google.android.feature.GOOGLE_EXPERIENCE":true,"android.software.ipsec_tunnels":true,"com.google.android.feature.EXCHANGE_6_2":true,"com.google.android.apps.photos.PIXEL_2018_PRELOAD":true,"android.hardware.sensor.assist":true,"com.google.android.feature.DREAMLINER":true,"android.hardware.audio.pro":true,"android.hardware.nfc.hcef":true,"android.hardware.nfc.uicc":true,"android.hardware.location.gps":true,"android.software.midi":true,"android.hardware.nfc.any":true,"android.hardware.nfc.hce":true,"android.hardware.wifi":true,"android.hardware.location":true,"android.hardware.vulkan.level":true,"android.hardware.wifi.aware":true,"android.software.secure_lock_screen":true,"android.hardware.telephony":true,"android.software.file_based_encryption":true,"glEsVersion":"3.2"},"ENVIRONMENT":{"getDataDirectory":"\/data","getDataSystemDirectory":"\/data\/system","getDownloadCacheDirectory":"\/data\/cache","getExternalStorageDirectory":"\/storage\/emulated\/0","getExternalStorageState":"mounted","getInternalMediaDirectories":"[\/system\/media, \/oem\/media, \/product\/media]","getLegacyExternalStorageDirectory":"\/sdcard","getOdmDirectory":"\/odm","getOemDirectory":"\/oem","getProductDirectory":"\/product","getProductServicesDirectory":"\/product_services","getRootDirectory":"\/system","getStorageDirectory":"\/storage","getSystemExtDirectory":"\/system_ext","getVendorDirectory":"\/vendor","isExternalStorageEmulated":true,"isExternalStorageLegacy":false,"isExternalStorageManager":false,"isExternalStorageRemovable":false},"SHARED_PREFERENCES":{"default":{"pref_key_hotspot":false,"pref_key_port_no":"8080","pref_key_password":"1234"}}}`

**Comment by umer0586** [comment]
```json
"STACK_TRACE": "java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available\n",
```
There isn't much info in the stack trace to find the cause. I have tested this app on other Android 12 device and it works without any crashing issue. It seems that Pixel3/Android12 is not properly installing the app otherwise the app would have crashed on Pixel6/Android13 :confused:

**Comment by umer0586** [comment]
I recently tested the app on **Pixel 3 Android 12 emulator** and it works fine, no crashing issue while navigating to settings tab. Maybe this issue is related to the device you are using :confused:

**Comment by bufferUnderrun** [comment]
thanks for the try
