### ISSUE TITLE
Can it be reliable for working 24/7

### ISSUE THREAD

**Issue by hacen-ai** [umer0586/AndroidSMSServer#2]
Hello,
First of all, great app it will help me a lot in my project, Thank you for sharing it.
Did you happend to try it in 24/7 envirement?
Other question please:
Can I use it on cellulaire connection (4G/3G) not the wifi?
Can the app continue working after the phone is locked (screen turnoff or in night)?

Thank you

**Comment by umer0586** [comment]
@hacen-ai 
> Did you happend to try it in 24/7 envirement?

No, I didn't tested the app in 24/6 environment

>Can I use it on cellulaire connection (4G/3G) not the wifi?

You cannot directly use cellular connections, but one workaround is to use one device as Wi-Fi hotspot and connecting your PC/Laptop and device containing AndroidSMSServer app to it

>Can the app continue working after the phone is locked (screen turnoff or in night)?

Yes, I tested it. It works when screen is off (sleeping)
