### ISSUE TITLE
cannot send message

### ISSUE THREAD

**Issue by longkoy732** [umer0586/AndroidSMSServer#3]
I cannot send message message using the app. I want to know to how to setup client and server

**Comment by umer0586** [comment]
> I cannot send message message using the app. I want to know to how to setup client and server

@longkoy732 
Make sure your Android Device and HTTP client are connected to same Wi-Fi network. In app press Start button you will see IP address and Port No above Start button something like `http://192.168.0.102:8081/sendSMS` , simply use this IP and port number to send http request to android device. Your device will have different IP

If your are using PHP then simply 
```php
<?php
	//open connection
	$ch = curl_init();

	
	curl_setopt($ch,CURLOPT_URL, "http://<Put Ip Address Here>:<Put Port No Here>/sendSMS");
	curl_setopt($ch,CURLOPT_POST, true);
	curl_setopt($ch,CURLOPT_POSTFIELDS, http_build_query(
		array(

			'phone'  => "03476030148",
		    	'message' => "Your verification code is 1234"
			)
		));

	//So that curl_exec returns the contents of the cURL; rather than echoing it
	curl_setopt($ch,CURLOPT_RETURNTRANSFER, true); 

	//execute post
	$jsonResponse = curl_exec($ch);
	echo $jsonResponse;

?>
```

**Comment by longkoy732** [comment]
Thank you very much. It's now working

**Comment by longkoy732** [comment]
{ "exception" : "Neither user 10542 nor current process has android.permission.READ_PHONE_STATE.", "status" : "Exception occurred while sending message" }. I have this error in the other phone

**Comment by umer0586** [comment]
> Thank you very much. It's now working. Can i customize this app that i will use my own server? Is this capable to receive SMS when the contact reply that you send a message and display to a page just like an inbox page in website?

@longkoy732 If you own a **Local Server** then Yes, but if your using a server from **Cloud** then you cannot. Secondly this app currently isn't capable to forward received SMS to URL.

**Comment by umer0586** [comment]
> { "exception" : "Neither user 10542 nor current process has android.permission.READ_PHONE_STATE.", "status" : "Exception occurred while sending message" }. I have this error in the other phone

@longkoy732 On which version of Android you got this error message ?

**Comment by longkoy732** [comment]
> > { "exception" : "Neither user 10542 nor current process has android.permission.READ_PHONE_STATE.", "status" : "Exception occurred while sending message" }. I have this error in the other phone
> 
> @longkoy732 On which version of Android you got this error message ?

Android 8.1.0

**Comment by longkoy732** [comment]
> > Thank you very much. It's now working. Can i customize this app that i will use my own server? Is this capable to receive SMS when the contact reply that you send a message and display to a page just like an inbox page in website?
> 
> @longkoy732 If you own a **Local Server** then Yes, but if your using a server from **Cloud** then you cannot. Secondly this app currently isn't capable to forward received SMS to URL.

How can i intergrate to forward received SMS to URL? do you have any referrence? Do you have any plan to apply it to this app?

**Comment by umer0586** [comment]
> > > Thank you very much. It's now working. Can i customize this app that i will use my own server? Is this capable to receive SMS when the contact reply that you send a message and display to a page just like an inbox page in website?
> > 
> > 
> > @longkoy732 If you own a **Local Server** then Yes, but if your using a server from **Cloud** then you cannot. Secondly this app currently isn't capable to forward received SMS to URL.
> 
> How can i intergrate to forward received SMS to URL? do you have any referrence? Do you have any plan to apply it to this app?

I have a plan but currently I don't have much time to implement this feature, Anyone with Android development knowledge could easily implement this feature by contributing to this repo.

**Comment by umer0586** [comment]
> How can i intergrate to forward received SMS to URL? do you have any referrence? Do you have any plan to apply it to this app?

@longkoy732 
I have a plan but currently I don't have much time to implement this feature, Anyone with Android development knowledge could easily implement this feature by contributing to this repo.
