### ISSUE TITLE
[Feature Request] MMS Messages

### ISSUE THREAD

**Issue by Artucuno** [umer0586/AndroidSMSServer#5]
Hey, are you able to add MMS messaging and have it upload either a local file or bytes?

**Comment by umer0586** [comment]
> Hey, are you able to add MMS messaging and have it upload either a local file or bytes?

This app was indented for SMS only, so no plan to add MMS feature. If you are looking to send small file over SMS you should convert file to `Base64` and send `Base64` text via SMS. But at receiver end `Base64` to file conversion would be required
