### ISSUE TITLE
Access the server remotely

### ISSUE THREAD

**Issue by pranaycb** [umer0586/AndroidSMSServer#7]
Hi Umer. First of all thanks for your awesome project. Is there any option to access the web server remotely? I want to mean that we can access this server when both device is connected in same network. I want to connect this server from a device that is not connected same network. Is there any option to do that? Thanks in advanced 🥰🥰

**Comment by umer0586** [comment]
See [this comment](https://github.com/umer0586/AndroidSMSServer/issues/4#issuecomment-1266834899) by @gjphilander where he is able to connect the app from different network using some tunneling program with PHP server. But beside this there are some android projects available on github which allow apps to send SMS over internet via firebase push or polling.
